# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# Scrollback
scrollback_lines 2000

# Load pywal colors — regenerated each time you run `wal -i`
include ~/.cache/wal/colors-kitty.conf

# Shell
shell zsh
shell_integration enabled

# Tab bar
tab_bar_style    fade
tab_bar_edge     bottom

# URL detection
url_style curly
detect_urls yes
